---
- name: deploy pulp
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: update all package
      package:
        name: "*"
        state: latest

    - name: install pulp repo file
      get_url:
        url: https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
        dest: /etc/yum.repos.d/rhel-pulp.repo

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - mongodb-server
        - qpid-cpp-client
        - qpid-cpp-server
        - qpid-cpp-server-linearstore
        - qpid-tools
        - "@pulp-server-qpid"
        - "@pulp-admin"

    - name: start and enable mongodb and qpidd
      service:
        name: "{{ item }}"
        state: running
        enabled: yes
      with_items:
        - mongod
        - qpidd

    - name: init pulp db
      command: pulp-manage-db
      become_user: apache

    - name: start and enable pulp services
      service:
        name: "{{ item }}"
        state: running
        enabled: yes
      with_items:
        - pulp_workers
        - pulp_celerybeat
        - pulp_resource_manager
        - httpd

